---
version: '3.8'
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    restart: unless-stopped
    container_name: nextcloud
    env_file: .env
    ports:
      - "8080:443"
    volumes:
      - ${CONFIG_VOLUME}:/config
      - ${DATA_VOLUME}:/data

networks:
  default:
    name: ${DOCKER_NETWORK}
    external: true
